package com.jucheonsu.port.infra.ppt;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.poi.sl.usermodel.TextParagraph;
import org.apache.poi.xslf.usermodel.XMLSlideShow;
import org.apache.poi.xslf.usermodel.XSLFSlide;
import org.apache.poi.xslf.usermodel.XSLFTextBox;
import org.apache.poi.xslf.usermodel.XSLFTextParagraph;
import org.apache.poi.xslf.usermodel.XSLFTextRun;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Service
public class PptExportServiceImpl implements PptExportService {

    private final ObjectMapper objectMapper = new ObjectMapper();

    public byte[] exportPortfolio(Long portfolioId, String layoutJson) {
        try (XMLSlideShow ppt = new XMLSlideShow(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            ppt.setPageSize(new Dimension(1280, 720));

            PptDeck deck = parseDeck(layoutJson, portfolioId);
            for (PptSlide slideData : deck.slides()) {
                if (slideData.type() == PptSlideType.COVER) {
                    createCoverSlide(ppt, slideData.title(), slideData.content(), deck.theme());
                } else {
                    createContentSlide(ppt, slideData.title(), slideData.content(), deck.theme(), slideData.type());
                }
            }

            if (deck.slides().isEmpty()) {
                createCoverSlide(ppt, "PORT Portfolio", "AI가 정리한 포트폴리오 #" + portfolioId, PptTheme.MODERN);
                createContentSlide(ppt, "Portfolio Summary", "내용이 없어 기본 템플릿으로 생성되었습니다.", PptTheme.MINIMAL, PptSlideType.PROJECT);
                createContentSlide(ppt, "Thank You", "Generated by PORT", PptTheme.BOLD, PptSlideType.THANK_YOU);
            }

            ppt.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("PPTX 생성에 실패했습니다.", e);
        }
    }

    private PptDeck parseDeck(String layoutJson, Long portfolioId) {
        if (!StringUtils.hasText(layoutJson)) {
            return defaultDeck(portfolioId);
        }

        try {
            JsonNode root = objectMapper.readTree(layoutJson);
            PptTheme theme = parseTheme(root.path("theme").asText("MODERN"));
            List<PptSlide> slides = new ArrayList<>();

            JsonNode slidesNode = root.path("slides");
            if (slidesNode.isArray()) {
                for (JsonNode node : slidesNode) {
                    slides.add(new PptSlide(
                            parseSlideType(node.path("type").asText("PROJECT")),
                            node.path("title").asText("Untitled"),
                            node.path("content").asText("")
                    ));
                }
            }

            return new PptDeck(theme, slides);
        } catch (Exception ignored) {
            return defaultDeck(portfolioId);
        }
    }

    private PptDeck defaultDeck(Long portfolioId) {
        return new PptDeck(
                PptTheme.MODERN,
                List.of(
                        new PptSlide(PptSlideType.COVER, "PORT Portfolio", "AI가 정리한 포트폴리오 #" + portfolioId),
                        new PptSlide(PptSlideType.PROJECT, "Portfolio Summary", "내용이 없어 기본 템플릿으로 생성되었습니다."),
                        new PptSlide(PptSlideType.THANK_YOU, "Thank You", "Generated by PORT")
                )
        );
    }

    private void createCoverSlide(XMLSlideShow ppt, String title, String subtitle, PptTheme theme) {
        XSLFSlide slide = ppt.createSlide();
        applyBackground(slide, theme);

        XSLFTextBox titleBox = slide.createTextBox();
        titleBox.setAnchor(new Rectangle(90, 190, 900, 90));
        setText(titleBox, title, 42, true, Color.WHITE);

        XSLFTextBox subtitleBox = slide.createTextBox();
        subtitleBox.setAnchor(new Rectangle(95, 295, 900, 60));
        setText(subtitleBox, subtitle, 20, false, new Color(230, 230, 230));
    }

    private void createContentSlide(XMLSlideShow ppt, String title, String content, PptTheme theme, PptSlideType type) {
        XSLFSlide slide = ppt.createSlide();
        applyBackground(slide, theme);

        Color textColor = theme == PptTheme.MINIMAL ? Color.BLACK : Color.WHITE;

        XSLFTextBox titleBox = slide.createTextBox();
        titleBox.setAnchor(new Rectangle(70, 55, 1050, 55));
        setText(titleBox, title, 30, true, textColor);

        XSLFTextBox bodyBox = slide.createTextBox();
        bodyBox.setAnchor(new Rectangle(75, 145, 1080, 430));
        String bodyText = type == PptSlideType.SKILLS ? formatSkills(content) : normalize(content);
        setText(bodyBox, bodyText, 16, false, textColor);
    }

    private void applyBackground(XSLFSlide slide, PptTheme theme) {
        Color color = switch (theme) {
            case MODERN -> new Color(124, 58, 237);
            case MINIMAL -> new Color(250, 250, 250);
            case BOLD -> new Color(17, 24, 39);
        };
        slide.getBackground().setFillColor(color);
    }

    private void setText(XSLFTextBox box, String text, double size, boolean bold, Color color) {
        box.clearText();
        XSLFTextParagraph paragraph = box.addNewTextParagraph();
        paragraph.setTextAlign(TextParagraph.TextAlign.LEFT);
        XSLFTextRun run = paragraph.addNewTextRun();
        run.setText(text);
        run.setFontFamily("Pretendard");
        run.setFontSize(size);
        run.setBold(bold);
        run.setFontColor(color);
    }

    private String normalize(String content) {
        if (content == null || content.isBlank()) {
            return "";
        }
        return content.length() > 1200 ? content.substring(0, 1200) + "..." : content;
    }

    private String formatSkills(String content) {
        if (!StringUtils.hasText(content)) {
            return "";
        }
        return content.replace(",", "\n• ").replace(";", "\n• ");
    }

    private PptTheme parseTheme(String value) {
        try {
            return PptTheme.valueOf(value.toUpperCase());
        } catch (Exception ignored) {
            return PptTheme.MODERN;
        }
    }

    private PptSlideType parseSlideType(String value) {
        try {
            return PptSlideType.valueOf(value.toUpperCase());
        } catch (Exception ignored) {
            return PptSlideType.PROJECT;
        }
    }

    private record PptDeck(PptTheme theme, List<PptSlide> slides) {
    }

    private record PptSlide(PptSlideType type, String title, String content) {
    }

    private enum PptSlideType {
        COVER,
        ABOUT,
        SKILLS,
        PROJECT,
        RESULT,
        THANK_YOU
    }
}
