package com.jucheonsu.port.infra.ppt;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType0Font;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

@Service
public class PptExportServiceImpl implements PptExportService {

    private static final float PAGE_WIDTH = 1280f;
    private static final float PAGE_HEIGHT = 720f;
    private static final float MARGIN_X = 88f;
    private static final float CONTENT_MAX_WIDTH = PAGE_WIDTH - (MARGIN_X * 2);
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public byte[] exportPortfolio(Long portfolioId, String layoutJson) {
        PptDeck deck = parseDeck(layoutJson, portfolioId);

        try (PDDocument document = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PDFont titleFont = resolveFont(document, true);
            PDFont bodyFont = resolveFont(document, false);

            if (deck.slides().isEmpty()) {
                deck = defaultDeck(portfolioId);
            }

            for (PptSlide slideData : deck.slides()) {
                if (slideData.type() == PptSlideType.COVER) {
                    createCoverSlide(document, slideData.title(), slideData.content(), deck.theme(), titleFont, bodyFont);
                } else {
                    createContentSlide(document, slideData.title(), slideData.content(), deck.theme(), slideData.type(), titleFont, bodyFont);
                }
            }

            document.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("PDF 생성에 실패했습니다.", e);
        }
    }

    private PptDeck parseDeck(String layoutJson, Long portfolioId) {
        if (!StringUtils.hasText(layoutJson)) {
            return defaultDeck(portfolioId);
        }

        try {
            JsonNode root = objectMapper.readTree(layoutJson);
            PptTheme theme = parseTheme(root.path("theme").asText("MODERN"));
            List<PptSlide> slides = new ArrayList<>();

            JsonNode slidesNode = root.path("slides");
            if (slidesNode.isArray()) {
                for (JsonNode node : slidesNode) {
                    slides.add(new PptSlide(
                            parseSlideType(node.path("type").asText("PROJECT")),
                            node.path("title").asText("Untitled"),
                            node.path("content").asText("")
                    ));
                }
            }

            return new PptDeck(theme, slides);
        } catch (Exception ignored) {
            return defaultDeck(portfolioId);
        }
    }

    private PptDeck defaultDeck(Long portfolioId) {
        return new PptDeck(
                PptTheme.MODERN,
                List.of(
                        new PptSlide(PptSlideType.COVER, "PORT Portfolio", "AI가 정리한 포트폴리오 #" + portfolioId),
                        new PptSlide(PptSlideType.PROJECT, "Portfolio Summary", "내용이 없어서 기본 템플릿으로 생성했습니다."),
                        new PptSlide(PptSlideType.THANK_YOU, "Thank You", "Generated by PORT")
                )
        );
    }

    private void createCoverSlide(PDDocument document, String title, String subtitle, PptTheme theme, PDFont titleFont, PDFont bodyFont) throws IOException {
        PDPage page = new PDPage(new PDRectangle(PAGE_WIDTH, PAGE_HEIGHT));
        document.addPage(page);

        try (PDPageContentStream content = new PDPageContentStream(document, page)) {
            drawBackground(content, theme);
            drawText(content, titleFont, 40, Color.WHITE, MARGIN_X, PAGE_HEIGHT - 170, 900, title);
            drawText(content, bodyFont, 20, new Color(230, 230, 230), MARGIN_X + 5, PAGE_HEIGHT - 240, 980, subtitle);
        }
    }

    private void createContentSlide(PDDocument document, String title, String contentText, PptTheme theme, PptSlideType type, PDFont titleFont, PDFont bodyFont) throws IOException {
        PDPage page = new PDPage(new PDRectangle(PAGE_WIDTH, PAGE_HEIGHT));
        document.addPage(page);

        Color textColor = theme == PptTheme.MINIMAL ? Color.BLACK : Color.WHITE;
        String bodyText = type == PptSlideType.SKILLS ? formatSkills(contentText) : normalize(contentText);

        try (PDPageContentStream content = new PDPageContentStream(document, page)) {
            drawBackground(content, theme);
            drawText(content, titleFont, 30, textColor, MARGIN_X, PAGE_HEIGHT - 80, 1050, title);
            drawText(content, bodyFont, 16, textColor, MARGIN_X, PAGE_HEIGHT - 140, CONTENT_MAX_WIDTH, bodyText);
        }
    }

    private void drawBackground(PDPageContentStream content, PptTheme theme) throws IOException {
        Color color = switch (theme) {
            case MODERN -> new Color(124, 58, 237);
            case MINIMAL -> new Color(250, 250, 250);
            case BOLD -> new Color(17, 24, 39);
        };
        content.setNonStrokingColor(color);
        content.addRect(0, 0, PAGE_WIDTH, PAGE_HEIGHT);
        content.fill();
    }

    private void drawText(PDPageContentStream content, PDFont font, float fontSize, Color color, float startX, float startY, float width, String text) throws IOException {
        if (!StringUtils.hasText(text)) {
            return;
        }

        content.beginText();
        content.setFont(font, fontSize);
        content.setNonStrokingColor(color);
        content.newLineAtOffset(startX, startY);

        float leading = fontSize * 1.45f;
        List<String> lines = wrapText(font, fontSize, width, text);
        for (int i = 0; i < lines.size(); i++) {
            if (i > 0) {
                content.newLineAtOffset(0, -leading);
            }
            content.showText(lines.get(i));
        }
        content.endText();
    }

    private List<String> wrapText(PDFont font, float fontSize, float maxWidth, String text) throws IOException {
        List<String> lines = new ArrayList<>();
        for (String paragraph : text.split("\\R", -1)) {
            if (!StringUtils.hasText(paragraph)) {
                lines.add("");
                continue;
            }
            StringBuilder current = new StringBuilder();
            for (String token : paragraph.split("\\s+")) {
                if (token.isBlank()) {
                    continue;
                }
                String candidate = current.isEmpty() ? token : current + " " + token;
                if (textWidth(font, fontSize, candidate) <= maxWidth) {
                    current.setLength(0);
                    current.append(candidate);
                    continue;
                }
                if (!current.isEmpty()) {
                    lines.add(current.toString());
                }
                if (textWidth(font, fontSize, token) <= maxWidth) {
                    current.setLength(0);
                    current.append(token);
                } else {
                    lines.addAll(splitLongWord(font, fontSize, maxWidth, token));
                    current.setLength(0);
                }
            }
            if (!current.isEmpty()) {
                lines.add(current.toString());
            }
        }
        return lines;
    }

    private List<String> splitLongWord(PDFont font, float fontSize, float maxWidth, String token) throws IOException {
        List<String> parts = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        for (char ch : token.toCharArray()) {
            String candidate = current + String.valueOf(ch);
            if (current.isEmpty() || textWidth(font, fontSize, candidate) <= maxWidth) {
                current.append(ch);
            } else {
                parts.add(current.toString());
                current.setLength(0);
                current.append(ch);
            }
        }
        if (!current.isEmpty()) {
            parts.add(current.toString());
        }
        return parts;
    }

    private float textWidth(PDFont font, float fontSize, String text) throws IOException {
        return font.getStringWidth(text) / 1000f * fontSize;
    }

    private PDFont resolveFont(PDDocument document, boolean bold) {
        List<String> candidates = List.of(
                "C:/Windows/Fonts/malgun.ttf",
                "C:/Windows/Fonts/malgunbd.ttf",
                "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
                "/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf",
                "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
                "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
                "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
        );

        for (String candidate : candidates) {
            try {
                if (Files.exists(Path.of(candidate))) {
                    return PDType0Font.load(document, new File(candidate));
                }
            } catch (Exception ignored) {
            }
        }

        return new PDType1Font(bold ? Standard14Fonts.FontName.HELVETICA_BOLD : Standard14Fonts.FontName.HELVETICA);
    }

    private String normalize(String content) {
        if (content == null || content.isBlank()) {
            return "";
        }
        return content.length() > 1200 ? content.substring(0, 1200) + "..." : content;
    }

    private String formatSkills(String content) {
        if (!StringUtils.hasText(content)) {
            return "";
        }
        return content.replace(",", "\n-").replace(";", "\n-");
    }

    private PptTheme parseTheme(String value) {
        try {
            return PptTheme.valueOf(value.toUpperCase());
        } catch (Exception ignored) {
            return PptTheme.MODERN;
        }
    }

    private PptSlideType parseSlideType(String value) {
        try {
            return PptSlideType.valueOf(value.toUpperCase());
        } catch (Exception ignored) {
            return PptSlideType.PROJECT;
        }
    }

    private record PptDeck(PptTheme theme, List<PptSlide> slides) {
    }

    private record PptSlide(PptSlideType type, String title, String content) {
    }

    private enum PptSlideType {
        COVER,
        ABOUT,
        SKILLS,
        PROJECT,
        RESULT,
        THANK_YOU
    }
}
