package com.jucheonsu.port.infra.ppt;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Component
public class PptSlideBuilder {

    private final ObjectMapper objectMapper;

    public PptSlideBuilder(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public String buildPresentationJson(Long portfolioId, String sourceText) {
        try {
            List<Map<String, Object>> slides = new ArrayList<>();
            String text = normalize(sourceText);
            slides.add(slide("COVER", "PORT Portfolio", preview(text, 180)));
            slides.add(slide("PROJECT", "Key Summary", toBullets(text)));
            slides.add(slide("RESULT", "Summary", toSummary(text)));
            slides.add(slide("THANK_YOU", "Thank You", "Generated by PORT"));

            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("portfolioId", portfolioId);
            payload.put("theme", "MODERN");
            payload.put("slides", slides);
            return objectMapper.writeValueAsString(payload);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to build PPT layout JSON.", e);
        }
    }

    private Map<String, Object> slide(String type, String title, String content) {
        Map<String, Object> slide = new LinkedHashMap<>();
        slide.put("type", type);
        slide.put("title", title);
        slide.put("content", content);
        return slide;
    }

    private String normalize(String sourceText) {
        if (!StringUtils.hasText(sourceText)) {
            return "";
        }
        return sourceText.replace("\r\n", "\n").trim();
    }

    private String preview(String text, int maxLength) {
        if (!StringUtils.hasText(text)) {
            return "PORT generated deck";
        }
        return text.length() > maxLength ? text.substring(0, maxLength) + "..." : text;
    }

    private String toBullets(String text) {
        if (!StringUtils.hasText(text)) {
            return "No selected sources.";
        }
        List<String> lines = text.lines()
                .map(String::trim)
                .filter(StringUtils::hasText)
                .filter(line -> !line.startsWith("#"))
                .limit(8)
                .toList();
        if (lines.isEmpty()) {
            return preview(text, 260);
        }
        return String.join("\n", lines);
    }

    private String toSummary(String text) {
        if (!StringUtils.hasText(text)) {
            return "No source content was provided, so a default slide deck was generated.";
        }
        long lineCount = text.lines().filter(StringUtils::hasText).count();
        return "The input content was organized into " + lineCount + " lines to compose the PPT layout.";
    }
}
